name: windows

on:
    push:
        branches:
            - '*'
        tags-ignore:
            - '*'
        pull_request:

jobs:
    raku:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2
            - uses: Raku/setup-raku@v1
            - name: Raku version check
              run: |
                raku -V
            - name: Install dependencies
              run: |
                zef install --/test --test-depends --deps-only .
                zef install --/test App::Prove6
            - name: Run tests
              run: |
                prove6 -l t
